apiVersion: v1
kind: Service
metadata:
  name: rest-server-service
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: rest-server
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer