FROM python:3.9-alpine

WORKDIR /

# Install Java and other dependencies
RUN apk add --no-cache openjdk11

# Set JAVA_HOME (optional, depends on the requirements of EpubCheck)
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk

COPY sonic-fact-437801-n6-1bf03fb77c7d.json /app/credentials.json
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/rest_server.py .
COPY src/redis_ops.py .
COPY src/messages.py .
COPY src/constants.py .
COPY src/utils.py .

EXPOSE 8000

CMD ["python", "rest_server.py"]
