FROM python:3.9-alpine

WORKDIR /app

# Install system dependencies
RUN apk add --no-cache ffmpeg

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/audio_stitcher.py .
COPY src/redis_ops.py .
COPY src/messages.py .
COPY src/constants.py .
COPY src/utils.py .

CMD ["python", "audio_stitcher.py"]
