FROM python:3.9-alpine

WORKDIR /app

COPY sonic-fact-437801-n6-1bf03fb77c7d.json /app/credentials.json
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/audio_stitcher.py .
COPY src/redis_ops.py .
COPY src/messages.py .
COPY src/constants.py .
COPY src/utils.py .

CMD ["python", "audio_stitcher.py"]
