FROM python:3.11-alpine

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/event_tracker.py .
COPY src/redis_ops.py .
COPY src/messages.py .
COPY src/constants.py .
COPY src/utils.py .

CMD ["python", "event_tracker.py"]
