FROM python:3.9-alpine

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/tts.py .
COPY src/redis_ops.py .
COPY src/messages.py .
COPY src/constants.py .
COPY src/utils.py .

CMD ["python", "tts.py"]
